baseUrl = "https://danilocianfrone.com/"
languageCode = "en-us"
theme = "cactus"
title = "ar3s3ru â€” Danilo Cianfrone"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4


[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

  [markup.highlight]
    style = "github"

[params]
  mainSection = "posts"
  colortheme = "classic"
  postsOnHomePage = 8
  description = "A collection of rants and silly thoughts, usually in Rust and Go (maybe Kotlin too)."

  [[params.social]]
    name = "github"
    link = "https://github.com/ar3s3ru"

  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/danilo-cianfrone"
